name: trying unittest

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: python:3.10-slim

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Uses your custom requirements.txt

    - name: Run unit tests
      run: python -m unittest test_calculator.py
