name: trying unittest

on:
  push:
    branches: 
      - main  # Triggers on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Specifies the OS for the GitHub runner

    container:
      image: python:3.10-slim  # Uses Python 3.10-slim docker image

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Checks out the code from the repo

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrades pip to the latest version
        pip install -r requirements.txt  # Installs all dependencies listed in requirements.txt

    - name: Run unit tests
      run: python -m unittest tests.py  # Runs the unit tests defined in tests.py
